### ISSUE TITLE
Able to login with incorrect password, even after logout and generally strange behaviours

### ISSUE THREAD

**Issue by CxRes** [jeff-zucker/solid-auth-cli#13]
I do not know how to put this even:
1) I tried logging in with incorrect credentials and got no `session` object.
1) I tried logging in with correct credentials, which worked!
1) I logged out and I tried logging in with incorrect credentials. I get the same `session` object as previously. It seems logout failed.
1) I logged out with 'solid-auth-client' (hoping to force the issue) and then tried to login with incorrect username, now the login failed. 
1) I tried logging in with incorrect password but correct username, I get back the old session object. 

This all is so strange that I am not sure what the bug is!

I am on Windows 10, though this should have no bearing on this. Node v12.16.1 LTS.

**Comment by jeff-zucker** [comment]
I'm pretty sure I know what is going on.  After the last changes in solid-cli I started saving the identity to disk.  I want to eliminate that because it mucks with the ability to have multiple sessions (e.g. when using solid-auth-cli in Data-Kitchen).  So I have been meaning to get in and fix that and this is even more motivation.  I hope to work on this in the next couple of days, I may ask you to test some things out.

**Comment by CxRes** [comment]
Good to know! I'll put off working on this till I hear back from you...

**Comment by jeff-zucker** [comment]
I've uploaded a new version of src/index.js which, for me fixes things albeit in a kludgy way.  I've overridden solid-cli.createSession within solid-auth-cli and fed the relyingParty the scope it needs as per your suggested fix.  I can remove the overridden method if and when the powers that be change solid-cli and/or oidc-rp.  That allowed me to remove the saving to disc of the identityManager which should eliminate the oddness you had with logins.  Could you give it a test and let me know?  Many thanks for all your help.

**Comment by CxRes** [comment]
LGTM!!!
